services:
  restaurant_db:
    image: mongo
    container_name: restaurant_db
    ports:
      - "27017:27017"
    networks:
      - app-network
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30

  api:
    build: ./api
    container_name: restaurant_api
    ports:
      - "4000:4000"
    networks:
      - app-network
    depends_on:
      - restaurant_db
    environment:
      - DATABASE_URL=mongodb://restaurant_db:27017/restaurant
      - CLIENT_TIMER=5000
      - WAITER_TIMER=5000
      - EATING_TIMER=5000
      - CLIENT_ENTRY_RATIO=5
      - NODE_ENV=development
    volumes:
      - ./api/src:/app/src
      - ./api/package.json:/app/package.json

  frontend:
    build: ./frontend
    container_name: restaurant_frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://restaurant_api:4000
    volumes:
      - ./frontend:/app

networks:
  app-network:
    driver: bridge
